# 基础配置
enable_cluster: false
enable_session_pool: false
# 单机节点配置
host: "127.0.0.1"
port: "6667"
username: "root"
password: "root"
# 集群节点配置
node_urls:
  - "127.0.0.1:6667"
  - "127.0.0.1:6668"
  - "127.0.0.1:6669"
# ssl配置
enable_thrift_ssl: false
use_ssl: false
ca_certs: ca_cert.pem
